name: Android CI

on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main, testing ]

jobs:

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Move properties file
        env:
          PROPERTIES: ${{ secrets.PROJECT_PROPERTIES }}
        run: |
          touch project.properties && echo "$PROPERTIES" > project.properties
      - name: Add google services
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $DATA > app/google-services.json
      - name: Add Google Map API Key
        env:
          MAP_API: ${{ secrets.GOOGLE_MAP_API_KEY }}
        run: |
          echo $MAP_API > app/src/main/res/values/key.xml
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Generate Report
        run: bash ./gradlew koverReport
      - name: Upload Report
        uses: actions/upload-artifact@v1
        with:
          name: Kover Report
          path: app/build/reports/kover/project-html/index.html

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Update properties file
        env:
          PROPERTIES: ${{ secrets.PROJECT_PROPERTIES }}
        run: |
          touch project.properties && echo "$PROPERTIES" > project.properties
      - name: Add google services
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $DATA > app/google-services.json
      - name: Add Google Map API Key
        env:
          MAP_API: ${{ secrets.GOOGLE_MAP_API_KEY }}
        run: |
          echo $MAP_API > app/src/main/res/values/key.xml
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
